server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service


#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
#    username: root
#    password: 123
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.yshen.model


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
##    间隔时间上限
#    lease-expiration-duration-in-seconds: 2