server:
  port: 88
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true